import re
import pdfplumber
import pandas as pd
from config import COLUMNAS


def extraer(pdf_path: str) -> pd.DataFrame:
    with pdfplumber.open(pdf_path) as pdf:
        for pagina in pdf.pages:
            texto = pagina.extract_text()
            if texto:
                lineas = _obtener_lineas_limpias(texto)
                df = _parsear_lineas(lineas)
                if not df.empty:
                    return df
    return pd.DataFrame(columns=COLUMNAS)


def _obtener_lineas_limpias(texto):
    ignorar_inicios = (
        "1 888", "pet owner", "species:", "breed:", "gender:",
        "age:", "patient id:", "attending vet", "idexx",
        "hematology", "generated by", "page", "account #",
        "test result reference value", "test result ref range",
        "(continued)", "rbc run", "wbc run", "download", "®",
    )
    lineas = []
    for linea in texto.split("\n"):
        limpia = linea.strip()
        if not limpia:
            continue
        if limpia.lower().startswith(ignorar_inicios):
            continue
        if re.match(r"^[A-ZÁÉÍÓÚÑ]+(?:\s+[A-ZÁÉÍÓÚÑ]+){1,3}$", limpia):
            continue
        if re.match(r"^\d{1,2}/\d{1,2}/\d{2,4}", limpia):
            continue
        lineas.append(limpia)
    return lineas


def _parsear_lineas(lineas):
    elementos = []

    for linea in lineas:
        tokens = linea.split()
        if not tokens:
            continue

        if _es_continuacion(linea):
            elementos.append({"tipo": "continuacion", "texto": linea})
            continue

        partes = _separar_columnas(tokens)
        if partes is None:
            continue

        item, resultado, referencia, flag = partes
        elementos.append({
            "tipo": "dato",
            "item": item,
            "resultado": resultado,
            "referencia": referencia,
            "flag": flag,
        })

    elementos = _fusionar_continuaciones(elementos)

    filas = []
    for el in elementos:
        if el["tipo"] == "dato":
            item = el["item"]
            referencia = el["referencia"]
            if item.startswith("Platelets"):
                item = "Platelets"
                if referencia == "- 484 K/µL":
                    referencia = "148 - 484 K/µL"
            elif item.startswith("PDW"):
                item = "PDW"
                if referencia == "- 19.4 fL":
                    referencia = "9.1 - 19.4 fL"
            filas.append({
                "item": item,
                "resultado": el["resultado"],
                "referencia": referencia,
                "flag": el["flag"],
            })

    return pd.DataFrame(filas)


def _es_continuacion(linea):
    return len(linea.split()) == 1 and not linea.replace(".", "").isdigit() and linea.strip() not in ("H", "L")


def _fusionar_continuaciones(elementos):
    resultado = []
    for el in elementos:
        if el["tipo"] == "continuacion":
            if resultado and resultado[-1]["tipo"] == "dato":
                resultado[-1]["item"] = (resultado[-1]["item"] + " " + el["texto"]).strip()
            else:
                resultado.append({"tipo": "dato", "item": el["texto"], "resultado": "", "referencia": "", "flag": ""})
        else:
            resultado.append(el)
    return resultado


def _separar_columnas(tokens):
    indices_numeros = [i for i, t in enumerate(tokens) if _es_numero(t)]
    if not indices_numeros:
        return None

    idx_resultado = indices_numeros[0]
    item = " ".join(tokens[:idx_resultado])

    if len(tokens) == idx_resultado + 1:
        resultado = tokens[idx_resultado]
        referencia = ""
        flag = ""
        return item, resultado, referencia, flag

    resultado = tokens[idx_resultado]
    resto = tokens[idx_resultado + 1:]

    referencia, flag = _separar_referencia_flag(resto)
    return item, resultado, referencia, flag


def _es_numero(token):
    token_limpio = token.replace(",", ".")
    try:
        float(token_limpio)
        return True
    except ValueError:
        return False


def _separar_referencia_flag(tokens):
    flag = ""
    if tokens and tokens[-1] in ("H", "L"):
        if not _es_unidad_falsa(tokens):
            flag = tokens.pop()

    referencia = " ".join(tokens)
    return referencia, flag


def _es_unidad_falsa(tokens):
    if len(tokens) < 2:
        return False
    penultimo = tokens[-2]
    return penultimo.endswith(("µ", "d", "f", "c", "m", "k", "K"))
